### ISSUE TITLE
Error with unicorn

### ISSUE THREAD

**Issue by Vooxelfr** [CoreyMSchafer/code_snippets#7]
Hello,

since the blueprint and configuration chapter i have this error when i launch the unicorn command

gunicorn flaskblog
[2018-05-09 15:47:16 +0200] [20254] [INFO] Starting gunicorn 19.8.1
[2018-05-09 15:47:16 +0200] [20254] [INFO] Listening at: http://127.0.0.1:8000 (20254)
[2018-05-09 15:47:16 +0200] [20254] [INFO] Using worker: sync
[2018-05-09 15:47:16 +0200] [20257] [INFO] Booting worker with pid: 20257
[2018-05-09 15:47:16 +0200] [20257] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/vince/VooxelFlaskEnv/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/vince/VooxelFlaskEnv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/vince/VooxelFlaskEnv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/vince/VooxelFlaskEnv/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/vince/VooxelFlaskEnv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/vince/VooxelFlaskEnv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/vince/VooxelFlaskEnv/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
ModuleNotFoundError: No module named 'flaskblog'
[2018-05-09 15:47:16 +0200] [20257] [INFO] Worker exiting (pid: 20257)
[2018-05-09 15:47:16 +0200] [20254] [INFO] Shutting down: Master
[2018-05-09 15:47:16 +0200] [20254] [INFO] Reason: Worker failed to boot.

I do not understand what to do with this.
Did anyone have the same issue?

Thank you for your great Flask Tutorial.

**Comment by CoreyMSchafer** [comment]
Hey there. I'm going to upload some deployment videos for the Flask and Django courses as soon as I can. Once I do, if you have any questions like this then feel free to ask in the comment section of those videos or send me an email.

**Comment by Vooxelfr** [comment]
Nice! I will be in the first viewer!
